# Generated by Django 4.2 on 2023-04-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_album_album_art_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.ImageField(upload_to='main_app/static/photos/%Y/%m/%d/'),
        ),
    ]
